version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    env_file:
      - docker.env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
