export default {
  PORT: process.env.PORT,
  FRONTEND_URL: process.env.FRONTEND_URL,
  API_HOST: process.env.API_HOST,
  MONGO_URI: process.env.MONGO_URI,
  SALT_ROUNDS: process.env.SALT_ROUNDS,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY,
  OTP_EXPIRY: process.env.OTP_EXPIRY,
  RUNTIME: process.env.RUNTIME,
  AWS_REGION:process.env.AWS_REGION,
  AWS_ACCESS_KEY_ID:process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY:process.env.AWS_SECRET_ACCESS_KEY,
  S3_BUCKET_NAME:process.env.S3_BUCKET_NAME,
  REDIS_URI: process.env.REDIS_URI
}